FROM node:alpine as development

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY tsconfig.json tsconfig.json
COPY nest-cli.json nest-cli.json
COPY apps/users/prisma ./prisma

RUN npm install -g pnpm
RUN pnpm install 
RUN pnpm prisma generate

COPY apps/users apps/users
COPY libs libs


RUN pnpm run build users

FROM node:alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install --prod

COPY --from=development /usr/src/app/dist ./dist

CMD [ "pnpm", "run", "start:prod", "dist/app/users/main" ]