services:
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: pnpm run start:dev users
    env_file:
      - ./apps/users/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app