services:
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: pnpm run start:dev users
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
